require('dotenv').config()
const {
  GITHUB_OWNER,
  GITHUB_REPOSITORY,
  GITHUB_COLLABORATOR,
  GITHUB_OWNER_TOKEN,
  GITHUB_COLLABORATOR_TOKEN,
  TRAVIS_COLLABORATOR_TOKEN,
  TRAVIS_OWNER_ACCESS_TOKEN,
  NPM_COLLABORATOR_TOKEN,
  SLACK_CHANNEL_ID,
  SLACK_OAUTH_TOKEN,
  CODACY_TOKEN,
  SNYK_TOKEN
} = process.env
module.exports = {
  GITHUB_OWNER,
  GITHUB_REPOSITORY,
  GITHUB_COLLABORATOR,
  GITHUB_OWNER_TOKEN,
  GITHUB_COLLABORATOR_TOKEN,
  TRAVIS_COLLABORATOR_TOKEN,
  TRAVIS_OWNER_ACCESS_TOKEN,
  NPM_COLLABORATOR_TOKEN,
  SLACK_CHANNEL_ID,
  SLACK_OAUTH_TOKEN,
  CODACY_TOKEN,
  SNYK_TOKEN
}
